### ISSUE TITLE
Rework timing

### ISSUE THREAD

**Issue by jelu** [DNS-OARC/drool#75]
Timing code is a bit of a mess:
- need to simplify
- add each mode as one function
- function pointer for the timing mode
- use usec as lowest (since that is what is in the PCAP)
- use `tracertstats` to check timing code with baseline from replayed PCAP

**Comment by Brian-Rojas** [comment]
Using the time multiply 0.5 or 0.9 I get error message:

network warning: Unable to keep up with timings (process cost 0.000000798, packet diff 0.000001, now 15045085.959774827, sleep to 15045085.959774231)

Any ideas why?
Thank you.

**Comment by jelu** [comment]
For that case it means that it overslept by 0.596u secs which can happen
because sleeping also costs CPU, and measuring the CPU usage also costs CPU.

Very hard to be exact when the time between captured packets are as low as
that.
