### ISSUE TITLE
Drool & capturing messages

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/drool#80]
During OARC 27 we were kicking ideas about Drool capturing messages.

Our use-case is to send the very same DNS query message to multiple resolvers and capture their answers for further processing.

Open questions I can see are:
* In what format will Drool save captured answers?
* How Drool should handle timeouts? (E.g. our tool "orchestrator" from respdiff v2 suite gives up after configured number of seconds and continues with another query.)
* Assuming that answers are written to separate PCAP for each target IP/port combination, how do we identify that question contained in packet #1 in INPUT_PCAP belongs to answers #2 in OUTPUT_PCAP_1 and #3 in OUTPUT_PCAP_2?

For answer postprocessing you might want to look at tools we developed already:
https://gitlab.labs.nic.cz/knot/resolver-benchmarking/tree/master/response_differences/respdiff

Respdiff v2 is conceptually chain of independent tools:
msgdiff: compare DNS answers
diffsum: summarize differences into textual report

Both tools work with database produced by tools which are invoked "earlier" in the pipeline, namely:
qprep: generate queries in wire format
orchestrator: send pre-generated wire format to servers and gather answers
Drool reading a PCAP might replace tools 1 and 2 (qprep and orchestrator) and then we could re-use analytic tool `msgdiff` we already have. (Please do not get scared by the LMDB, we do not depend on it in any way - it can be changed to whatever.)

Let me know if you are intereted in cooperation on this problem.

**Comment by jelu** [comment]
Finally some time to look at this and I can see cooperation here but I also see slightly different use cases; `drool` is more about performance of one system and `respdiff` is about differentials between many systems.

One approach might be to have `drool` output to the LMDB and store what it sent/received as `target` and what it found in the PCAP as `others`.

- Is there more documentation on the matching process?
- Is there more documentation on the LMDB?
- Have you considered adding performance and timing metrics?

> How Drool should handle timeouts?
```
client_pool client_ttl SECONDS_AS_FLOAT ;
      Set the time a client lives for, this is used to timeout clients
      in  case  the  target  does  not answer.  Default value is 0.05.
      Specified as a float meaning 0.2 would be 200 milliseconds.
```

**Comment by vcunat** [comment]
> Have you considered adding performance and timing metrics?

I think in future it might be interesting to measure latency of each query.  High differences between resolvers on the same query might indicate cases worth to inspect, and overall latency histograms might be even more interesting to compare between resolvers and between versions.

**Comment by pspacek** [comment]
>  One approach might be to have drool output to the LMDB and store what it sent/received as target and what it found in the PCAP as others.

In general, output from Drool to LMDB, or reading different formats in respdiff is a possibility.

The problem I see is with *not* sending queries to different resolvers in parallel. I think it would not work well. One setup we support and use with respdiff is comparing answers between "forwarder" and "iterator". I.e. one resolver forwards to the other and we compare answers from the two resolvers. If the query was not sent at the same time, we could get different answers just because of short TTLs and so on.

>    Is there more documentation on the matching process?

There is consise description below header "Msgdiff" and "Diffsum" in the README:
https://gitlab.labs.nic.cz/knot/resolver-benchmarking/blob/617e7796987682a4f585c09c78ba2d804b6d611d/response_differences/respdiff/README.rst#msgdiff
If it is not clear, please let me know and we will improve it!


>    Is there more documentation on the LMDB?

Not really because it is just implementation detail. We use LMDB as key-value store for blobs. In short:
* Each query has own ID which is sequence number incremented for each packet read from PCAP. This ID is used as key in databases.
* Data are in organized in separate databases inside one LMDB:
  * `queries` DB with format key = query seq no; value = wire format
  * `answers` DB with format key = query seq no; value = pickled Python dict with format
`{'resolver1': <msg in wire format>, 'resolver2': <msg>, 'resolver3': <msg>}`

We can change this format at will.


>    Have you considered adding performance and timing metrics?

We could certainly have use for timing data if Drool outputs them along with wire format blobs. I think it does not make much sense to implement some precise time measurement in current Python code.


BTW I did some experiments with latest version of respdiff and it seems that bottleneck *while testing resolvers* is not respdiff itself but network. Respdiff with 256 threads is able to saturate the test machine I have. According to `top` most of the time is spent in resolvers processes and not respdiff itself so it might be good enough for our use-case. (It now supports UDP/TCP/TLS transports and the same seems to apply to TCP as well.)

What do you think? Is it worth the effort?

**Comment by jelu** [comment]
> The problem I see is with not sending queries to different resolvers in parallel. I think it would not work well. One setup we support and use with respdiff is comparing answers between "forwarder" and "iterator". I.e. one resolver forwards to the other and we compare answers from the two resolvers. If the query was not sent at the same time, we could get different answers just because of short TTLs and so on.

For this to work, `respdiff` needs to be configured on how to match results because there will be a lot of different scenarios that it will have to cover. In your case you want to check TTL, in my case it can be as simple as; did we get an A back and is it the same as in the replayed PCAP?

>  If it is not clear, please let me know and we will improve it!

Documentation of the configuration file would be good, for example in `respdiff.cfg` for `[diff]` it says `# fields and comparison methods` but I can only see `criteria = ...` which just looks like fields.

> What do you think? Is it worth the effort?

I could see parts of this work for drool if some tools are made a bit more generalized and maybe change the format some (don't know how easy it would be to write pickled data in C, want to keep dependencies to the minimum if possible).

Also, the feature to send the same query to multiple targets and store the results tied to an ID is all within what drool should be able to do (just not there yet).

Biggest issue I see is that your developing these tools for a specific purpose and doing it in a more generalized way will require more time on your part and may block specific measurements in the future.

**Comment by pspacek** [comment]
I'm confused by your last reply.

To clear this up, let me restate what is my ask: We (= respdiff/Knot Resolver developers) want to send "the same blob" (query) to multiple endpoints and collect back results - this is all we need. Right now we have tool to do that written in Python and I was wondering whether this is something Drool can/wants to do.

Are you saying that you want to use respdiff suite for some analyses? If it is the case, I'm glad to hear that!

Respdiff is literally a "suite" of tools, so you can mix and match. The sole purpose of msgdiff tool is to compare answers for the same query and to detect mismatches. If you want something similar, then we can easily extend msgdiff.

If you want some other type of analysis, then it could be a separate utility which would consume the same input format as msgdiff (and other tools). For example, colleague of mine extended respdiff suite to measure latency and added tool which consumes the same format as msgdiff but produces latency graphs. (Surprisingly, it gives reasonable results despite measuring time in Python.)

You can read more about this
https://gitlab.labs.nic.cz/knot/resolver-benchmarking/merge_requests/22#note_66701

So, to conclude, I think that we can find way to connect Drool with other tools, all we need is to agree on a shared data format.

**Comment by jelu** [comment]
Ah, thanks for clearing it up. Yeah `drool` should be able to do that so I will work towards that.

One of the next big things to do for `drool` is to analyze the answer back and I think `respdiff`/`msgdiff` can work.

As for format, if LMDB shouldn't be a problem.

**Comment by jelu** [comment]
This can be solved with new outputs in `dnsjit`, see DNS-OARC/dnsjit#10.
