### ISSUE TITLE
IPv6 client_pool target does not work

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/drool#87]
Hello,

it seems that IPv6 addresses in client pool target are not processed properly. Whenever I specify an IPv6 address as target, I end up getting lot of errors like this:

```
2017-11-14 12:30:45 client_pool.c:0490 network error: client start/connect failed
2017-11-14 12:30:45 client_pool.c:0518 network error: unable to create client, query requeued
```

Debug log does not give more information than this.

**Comment by jelu** [comment]
Really wish I had native IPv6 support in my development environments... will look at it!

**Comment by pspacek** [comment]
Seems to work, thank you!
